Card.destroy_all
Card.create!(name: "Aegislash", imageUrl: "http://cdn.bulbagarden.net/upload/a/ad/681Aegislash.png")
Card.create!(name: "Aerodactyl", imageUrl: "http://cdn.bulbagarden.net/upload/e/e8/142Aerodactyl.png")
Card.create!(name: "Alakazam", imageUrl: "http://cdn.bulbagarden.net/upload/c/cc/065Alakazam.png")
Card.create!(name: "Arcanine", imageUrl: "http://cdn.bulbagarden.net/upload/b/b8/059Arcanine.png")
Card.create!(name: "Articuno", imageUrl: "http://cdn.bulbagarden.net/upload/4/4e/144Articuno.png")
Card.create!(name: "Blastoise", imageUrl: "http://cdn.bulbagarden.net/upload/0/02/009Blastoise.png")
Card.create!(name: "Blaziken", imageUrl: "http://cdn.bulbagarden.net/upload/9/90/257Blaziken.png")
Card.create!(name: "Bulbasaur", imageUrl: "http://cdn.bulbagarden.net/upload/2/21/001Bulbasaur.png")
Card.create!(name: "Butterfree", imageUrl: "http://cdn.bulbagarden.net/upload/d/d1/012Butterfree.png")
Card.create!(name: "Caterpie", imageUrl: "http://cdn.bulbagarden.net/upload/5/5d/010Caterpie.png")
Card.create!(name: "Charizard", imageUrl: "http://cdn.bulbagarden.net/upload/7/7e/006Charizard.png")
Card.create!(name: "Chesnaught", imageUrl: "http://cdn.bulbagarden.net/upload/1/18/652Chesnaught.png")
Card.create!(name: "Chikorita", imageUrl: "http://cdn.bulbagarden.net/upload/b/bf/152Chikorita.png")
Card.create!(name: "Combee", imageUrl: "http://cdn.bulbagarden.net/upload/b/b6/415Combee.png")
Card.create!(name: "Corsola", imageUrl: "http://cdn.bulbagarden.net/upload/f/fc/222Corsola.png")
Card.create!(name: "Cubchoo", imageUrl: "http://cdn.bulbagarden.net/upload/7/72/613Cubchoo.png")
Card.create!(name: "Delphox", imageUrl: "http://cdn.bulbagarden.net/upload/2/21/655Delphox.png")
Card.create!(name: "Dewgong", imageUrl: "http://cdn.bulbagarden.net/upload/c/c7/087Dewgong.png")
Card.create!(name: "Dialga", imageUrl: "http://cdn.bulbagarden.net/upload/8/8a/483Dialga.png")
Card.create!(name: "Dragonite", imageUrl: "http://cdn.bulbagarden.net/upload/8/8b/149Dragonite.png")
Card.create!(name: "Dratini", imageUrl: "http://cdn.bulbagarden.net/upload/c/cc/147Dratini.png")
Card.create!(name: "Ducklett", imageUrl: "http://cdn.bulbagarden.net/upload/4/4b/580Ducklett.png")
Card.create!(name: "Eevee", imageUrl: "http://cdn.bulbagarden.net/upload/e/e2/133Eevee.png")
Card.create!(name: "Entei", imageUrl: "http://cdn.bulbagarden.net/upload/f/f9/244Entei.png")
Card.create!(name: "Espurr", imageUrl: "http://cdn.bulbagarden.net/upload/0/09/677Espurr.png")
Card.create!(name: "Fenniken", imageUrl: "http://cdn.bulbagarden.net/upload/3/3d/653Fennekin.png")
Card.create!(name: "Flabébé", imageUrl: "http://cdn.bulbagarden.net/upload/5/52/669Flab%C3%A9b%C3%A9.png")
Card.create!(name: "Flareon", imageUrl: "http://cdn.bulbagarden.net/upload/d/dd/136Flareon.png")
Card.create!(name: "Gardevoir", imageUrl: "http://cdn.bulbagarden.net/upload/9/99/282Gardevoir.png")
Card.create!(name: "Gastly", imageUrl: "http://cdn.bulbagarden.net/upload/c/ca/092Gastly.png")
Card.create!(name: "Gengar", imageUrl: "http://cdn.bulbagarden.net/upload/c/c6/094Gengar.png")
Card.create!(name: "Geodude", imageUrl: "http://cdn.bulbagarden.net/upload/9/98/074Geodude.png")
Card.create!(name: "Glaceon", imageUrl: "http://cdn.bulbagarden.net/upload/2/23/471Glaceon.png")
Card.create!(name: "Gorebyss", imageUrl: "http://cdn.bulbagarden.net/upload/3/37/368Gorebyss.png")
Card.create!(name: "Gothita", imageUrl: "http://cdn.bulbagarden.net/upload/7/71/574Gothita.png")
Card.create!(name: "Gulpin", imageUrl: "http://cdn.bulbagarden.net/upload/f/f0/316Gulpin.png")
Card.create!(name: "Gyardos", imageUrl: "http://cdn.bulbagarden.net/upload/4/41/130Gyarados.png")
Card.create!(name: "Haunter", imageUrl: "http://cdn.bulbagarden.net/upload/6/62/093Haunter.png")
Card.create!(name: "Horsea", imageUrl: "http://cdn.bulbagarden.net/upload/5/5a/116Horsea.png")
Card.create!(name: "Houndoom", imageUrl: "http://cdn.bulbagarden.net/upload/5/51/229Houndoom.png")
Card.create!(name: "Illumise", imageUrl: "http://cdn.bulbagarden.net/upload/5/55/314Illumise.png")
Card.create!(name: "Ivysaur", imageUrl: "http://cdn.bulbagarden.net/upload/7/73/002Ivysaur.png")
Card.create!(name: "Jirachi", imageUrl: "http://cdn.bulbagarden.net/upload/8/85/385Jirachi.png")
Card.create!(name: "Jynx", imageUrl: "http://cdn.bulbagarden.net/upload/7/7c/124Jynx.png")
Card.create!(name: "Latias", imageUrl: "http://cdn.bulbagarden.net/upload/2/24/380Latias.png")
Card.create!(name: "Latios", imageUrl: "http://cdn.bulbagarden.net/upload/5/52/381Latios.png")
Card.create!(name: "Leafeon", imageUrl: "http://cdn.bulbagarden.net/upload/f/f5/470Leafeon.png")
Card.create!(name: "Litleo", imageUrl: "http://cdn.bulbagarden.net/upload/1/1f/667Litleo.png")
Card.create!(name: "Lucario", imageUrl: "http://cdn.bulbagarden.net/upload/d/d7/448Lucario.png")
Card.create!(name: "Lugia", imageUrl: "http://cdn.bulbagarden.net/upload/4/44/249Lugia.png")
Card.create!(name: "Machamp", imageUrl: "http://cdn.bulbagarden.net/upload/8/8f/068Machamp.png")
Card.create!(name: "Marowak", imageUrl: "http://cdn.bulbagarden.net/upload/9/98/105Marowak.png")
Card.create!(name: "Meowstic", imageUrl: "http://cdn.bulbagarden.net/upload/a/a6/678Meowstic.png")
Card.create!(name: "Metagross", imageUrl: "http://cdn.bulbagarden.net/upload/0/05/376Metagross.png")
Card.create!(name: "Mew", imageUrl: "http://cdn.bulbagarden.net/upload/b/b1/151Mew.png")
Card.create!(name: "Mewtwo", imageUrl: "http://cdn.bulbagarden.net/upload/7/78/150Mewtwo.png")
Card.create!(name: "Minccino", imageUrl: "http://cdn.bulbagarden.net/upload/e/ec/572Minccino.png")
Card.create!(name: "Mr. Mime", imageUrl: "http://cdn.bulbagarden.net/upload/e/ec/122Mr._Mime.png")
Card.create!(name: "Oddish", imageUrl: "http://cdn.bulbagarden.net/upload/4/43/043Oddish.png")
Card.create!(name: "Pancham", imageUrl: "http://cdn.bulbagarden.net/upload/1/1c/674Pancham.png")
Card.create!(name: "Petilil", imageUrl: "http://cdn.bulbagarden.net/upload/0/0b/548Petilil.png")
Card.create!(name: "Pikachu", imageUrl: "http://cdn.bulbagarden.net/upload/0/0d/025Pikachu.png")
Card.create!(name: "Porygon2", imageUrl: "http://cdn.bulbagarden.net/upload/9/99/233Porygon2.png")
Card.create!(name: "Purrloin", imageUrl: "http://cdn.bulbagarden.net/upload/4/46/509Purrloin.png")
Card.create!(name: "Rayquaza", imageUrl: "http://cdn.bulbagarden.net/upload/e/e4/384Rayquaza.png")
Card.create!(name: "Salamence", imageUrl: "http://cdn.bulbagarden.net/upload/4/41/373Salamence.png")
Card.create!(name: "Scatterbug", imageUrl: "http://cdn.bulbagarden.net/upload/d/d3/664Scatterbug.png")
Card.create!(name: "Scizor", imageUrl: "http://cdn.bulbagarden.net/upload/5/55/212Scizor.png")
Card.create!(name: "Scizor", imageUrl: "http://cdn.bulbagarden.net/upload/5/55/212Scizor.png")
Card.create!(name: "Scraggy", imageUrl: "http://cdn.bulbagarden.net/upload/d/dc/559Scraggy.png")
Card.create!(name: "Scyther", imageUrl: "http://cdn.bulbagarden.net/upload/b/ba/123Scyther.png")
Card.create!(name: "Seel", imageUrl: "http://cdn.bulbagarden.net/upload/1/1f/086Seel.png")
Card.create!(name: "Servine", imageUrl: "http://cdn.bulbagarden.net/upload/7/73/496Servine.png")
Card.create!(name: "Shinx", imageUrl: "http://cdn.bulbagarden.net/upload/3/32/403Shinx.png")
Card.create!(name: "Skarmory", imageUrl: "http://cdn.bulbagarden.net/upload/3/35/227Skarmory.png")
Card.create!(name: "Skiddo", imageUrl: "http://cdn.bulbagarden.net/upload/5/5d/672Skiddo.png")
Card.create!(name: "Slurpuff", imageUrl: "http://cdn.bulbagarden.net/upload/8/8d/685Slurpuff.png")
Card.create!(name: "Snivy", imageUrl: "http://cdn.bulbagarden.net/upload/7/75/495Snivy.png")
Card.create!(name: "Snorlax", imageUrl: "http://cdn.bulbagarden.net/upload/f/fb/143Snorlax.png")
Card.create!(name: "Spewpa", imageUrl: "http://cdn.bulbagarden.net/upload/b/b7/665Spewpa.png")
Card.create!(name: "Spheal", imageUrl: "http://cdn.bulbagarden.net/upload/9/9f/363Spheal.png")
Card.create!(name: "Spritzee", imageUrl: "http://cdn.bulbagarden.net/upload/6/66/682Spritzee.png")
Card.create!(name: "Squirtle", imageUrl: "http://cdn.bulbagarden.net/upload/3/39/007Squirtle.png")
Card.create!(name: "Suicune", imageUrl: "http://cdn.bulbagarden.net/upload/d/da/245Suicune.png")
Card.create!(name: "Sylveon", imageUrl: "http://cdn.bulbagarden.net/upload/e/e8/700Sylveon.png")
Card.create!(name: "Teddiursa", imageUrl: "http://cdn.bulbagarden.net/upload/e/e9/216Teddiursa.png")
Card.create!(name: "Togepi", imageUrl: "http://cdn.bulbagarden.net/upload/6/6b/175Togepi.png")
Card.create!(name: "Torchic", imageUrl: "http://cdn.bulbagarden.net/upload/9/91/255Torchic.png")
Card.create!(name: "Tympole", imageUrl: "http://cdn.bulbagarden.net/upload/c/c9/535Tympole.png")
Card.create!(name: "Tyranitar", imageUrl: "http://cdn.bulbagarden.net/upload/8/82/248Tyranitar.png")
Card.create!(name: "Umbreon", imageUrl: "http://cdn.bulbagarden.net/upload/3/3d/197Umbreon.png")
Card.create!(name: "Vanillite", imageUrl: "http://cdn.bulbagarden.net/upload/3/3f/582Vanillite.png")
Card.create!(name: "Venusaur", imageUrl: "http://cdn.bulbagarden.net/upload/a/ae/003Venusaur.png")
Card.create!(name: "Victini", imageUrl: "http://cdn.bulbagarden.net/upload/6/60/494Victini.png")
Card.create!(name: "Vivillon", imageUrl: "http://cdn.bulbagarden.net/upload/4/4c/666Vivillon.png")
Card.create!(name: "Weedle", imageUrl: "http://cdn.bulbagarden.net/upload/d/df/013Weedle.png")
Card.create!(name: "Xerneas", imageUrl: "http://cdn.bulbagarden.net/upload/1/13/716Xerneas.png")
Card.create!(name: "Zapdos", imageUrl: "http://cdn.bulbagarden.net/upload/e/e3/145Zapdos.png")
Card.create!(name: "Zorua", imageUrl: "http://cdn.bulbagarden.net/upload/2/2b/570Zorua.png")
Card.create!(name: "Zygarde", imageUrl: "http://cdn.bulbagarden.net/upload/3/3a/718Zygarde.png")



# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
